name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-10.13

    steps:
    - uses: actions/checkout@v2
    - run: brew install python
    - run: pip install requests
    - name: Install xcode-install
      run: gem install xcode-install
#    - name: List possible Xcode version
#      run: xcversion list
    - name: Install xcode 11.7
      run: xcversion install 11.7
    - name: Xcode Version
      run: xcodebuild -version
    - name: Build and Test
      run: |
        xcodebuild -scheme standard-swift -sdk iphonesimulator -derivedDataPath Build/ -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.1' -enableCodeCoverage YES clean build test
        cd Build/Build/ProfileData
        cd $(ls -d */|head -n 1)
        directory=${PWD##*/} 
        pathCoverage=Build/Build/ProfileData/${directory}/Coverage.profdata
        cd ../../../../
        xcrun llvm-cov export -format="lcov" -instr-profile $pathCoverage Build/Build/Products/Debug-iphonesimulator/standard-swift.app/standard-swift > info.lcov
        bash <(curl https://codecov.io/bash)
        python request.py
        ./upstream.sh
